import { ref, computed } from 'vue';

// Translations
const enTranslations = {
  'nav.findATVs': 'Find ATVs',
  'nav.sellMyATV': 'Sell my ATV',
  'nav.research': 'Research',
  'nav.atvDealers': 'ATV dealers',
  'nav.blog': 'Blog',
  'nav.login': 'Log in',
  'nav.search': 'Search',
  'hero.title': 'Find your perfect ATV',
  'hero.subtitle': 'Browse thousands of ATVs for sale from dealers and private sellers',
  'hero.searchPlaceholder': 'Enter keywords (e.g., Honda, Yamaha)',
  'hero.zipPlaceholder': 'Enter ZIP code',
  'hero.radius': 'Radius',
  'hero.onlineListings': 'Include online listings',
  'hero.searchButton': 'Search ATVs',
  'hero.sellLink': 'Sell your ATV',
  'brands.title': 'ATVs for every outdoor adventure',
  'brands.makes': 'Makes',
  'brands.types': 'Types',
  'brands.seeAll': 'See all makes',
  'featured.title': 'Featured listings',
  'featured.viewAll': 'View All Featured',
  'featured.miles': 'miles',
  'sell.title': 'Sell your ATV',
  'sell.description': 'List your ATV for free and reach thousands of potential buyers',
  'sell.button': 'List Your ATV',
  'sell.today': 'List your ATV today',
  'buyOnline.title': 'Buy online',
  'buyOnline.description': 'Purchase ATVs from verified dealers with secure transactions',
  'buyOnline.button': 'Buy Now',
  'info.title': 'Find ATVs for Sale on ATV Trader',
  'info.description': 'ATV Trader is the leading marketplace for buying and selling all-terrain vehicles.',
  'footer.makes': 'Top Four Wheeler Makes',
  'footer.models': 'Top Four Wheeler Make/Models',
  'footer.types': 'Top Four Wheeler Types',
  'footer.copyright': '© 2025 ATV Trader. All rights reserved.',
  'findATVs.title': 'Find ATVs',
  'findATVs.results': 'ATVs for sale',
  'findATVs.noResults': 'No ATVs found matching your criteria',
  'listing.call': 'Call',
  'listing.year': 'year',
  'listing.mileage': 'km',
  'filters.manufacturer': 'Manufacturer',
  'filters.selectManufacturer': 'Select manufacturer',
  'filters.model': 'Model',
  'filters.modelName': 'Model name',
  'filters.priceGEL': 'Price (GEL)',
  'filters.yearOfManufacture': 'Year of Manufacture',
  'filters.mileageKm': 'Mileage (km)',
  'filters.condition': 'Condition',
  'filters.selectCondition': 'Select condition',
  'filters.new': 'New',
  'filters.excellent': 'Excellent',
  'filters.good': 'Good',
  'filters.fair': 'Fair',
  'filters.needsRepair': 'Needs Repair',
  'filters.engineSize': 'Engine Size',
  'filters.selectEngineSize': 'Select engine size',
  'filters.location': 'Location',
  'filters.selectCity': 'Select city',
  'filters.category': 'Category',
  'filters.selectCategory': 'Select category',
  'filters.sport': 'Sport',
  'filters.utility': 'Utility',
  'filters.youth': 'Youth',
  'filters.touring': 'Touring',
  'filters.racing': 'Racing',
  'filters.recreational': 'Recreational',
  'filters.applyFilters': 'Apply Filters',
  'filters.clearFilters': 'Clear Filters',
  'login.title': 'Log in to your account',
  'login.email': 'Email',
  'login.password': 'Password',
  'login.button': 'Sign in',
  'login.forgotPassword': 'Forgot your password?',
  'login.noAccount': "Don't have an account?",
  'login.signUp': 'Sign up',
  'sellMyATV.hero.title': 'Sell Your ATV',
  'sellMyATV.hero.subtitle': 'Reach thousands of buyers nationwide',
  'sellMyATV.hero.button': 'Start Selling',
  'contact.title': 'Contact Us',
  'about.title': 'About ATV Trader',
  'terms.title': 'Terms of Service',
  'privacy.title': 'Privacy Policy',
  'signup.title': 'Create your account',
  'blog.title': 'Blog',
  'research.title': 'Research',
  'dealers.title': 'ATV Dealers',
};

const kaTranslations = {
  'nav.findATVs': 'კვადროების ძებნა',
  'nav.sellMyATV': 'ჩემი კვადროს გაყიდვა',
  'nav.research': 'კვლევა',
  'nav.atvDealers': 'კვადროების დილერები',
  'nav.blog': 'ბლოგი',
  'nav.login': 'შესვლა',
  'nav.search': 'ძებნა',
  'hero.title': 'იპოვეთ თქვენი იდეალური კვადრო',
  'hero.subtitle': 'დაათვალიერეთ ათასობით კვადრო გასაყიდად დილერებისა და კერძო გამყიდველებისგან',
  'hero.searchPlaceholder': 'შეიყვანეთ საძიებო სიტყვები (მაგ., Honda, Yamaha)',
  'hero.zipPlaceholder': 'შეიყვანეთ ZIP კოდი',
  'hero.radius': 'რადიუსი',
  'hero.onlineListings': 'ონლაინ განცხადებების ჩათვლით',
  'hero.searchButton': 'კვადროების ძებნა',
  'hero.sellLink': 'გაყიდეთ თქვენი კვადრო',
  'brands.title': 'კვადროები ყველა გარე თავგადასავლისთვის',
  'brands.makes': 'მარკები',
  'brands.types': 'ტიპები',
  'brands.seeAll': 'ყველა მარკის ნახვა',
  'featured.title': 'გამორჩეული განცხადებები',
  'featured.viewAll': 'ყველა გამორჩეულის ნახვა',
  'featured.miles': 'მილი',
  'sell.title': 'გაყიდეთ თქვენი კვადრო',
  'sell.description': 'განათავსეთ თქვენი კვადრო უფასოდ და მიაღწიეთ ათასობით პოტენციურ მყიდველს',
  'sell.button': 'განათავსეთ კვადრო',
  'sell.today': 'განათავსეთ თქვენი კვადრო დღესვე',
  'buyOnline.title': 'ონლაინ ყიდვა',
  'buyOnline.description': 'შეიძინეთ კვადროები დადასტურებული დილერებისგან უსაფრთხო ტრანზაქციებით',
  'buyOnline.button': 'ახლავე იყიდეთ',
  'info.title': 'იპოვეთ კვადროები გასაყიდად ATV Trader-ზე',
  'info.description': 'ATV Trader არის წამყვანი მარკეტპლეისი ყველა ტიპის ტრანსპორტის ყიდვა-გაყიდვისთვის.',
  'footer.makes': 'ტოპ ოთხბორბლიანის მარკები',
  'footer.models': 'ტოპ ოთხბორბლიანის მარკა/მოდელები',
  'footer.types': 'ტოპ ოთხბორბლიანის ტიპები',
  'footer.copyright': '© 2025 ATV Trader. ყველა უფლება დაცულია.',
  'findATVs.title': 'კვადროების ძებნა',
  'findATVs.results': 'კვადროები გასაყიდად',
  'findATVs.noResults': 'თქვენს კრიტერიუმებს შესაბამისი კვადროები ვერ მოიძებნა',
  'listing.call': 'დარეკვა',
  'listing.year': 'წ.',
  'listing.mileage': 'კმ',
  'filters.manufacturer': 'მწარმოებელი',
  'filters.selectManufacturer': 'აირჩიეთ მწარმოებელი',
  'filters.model': 'მოდელი',
  'filters.modelName': 'მოდელის სახელი',
  'filters.priceGEL': 'ფასი (ლარი)',
  'filters.yearOfManufacture': 'გამოშვების წელი',
  'filters.mileageKm': 'გარბენი (კმ)',
  'filters.condition': 'მდგომარეობა',
  'filters.selectCondition': 'აირჩიეთ მდგომარეობა',
  'filters.new': 'ახალი',
  'filters.excellent': 'ძალიან კარგი',
  'filters.good': 'კარგი',
  'filters.fair': 'საშუალო',
  'filters.needsRepair': 'საჭიროებს შეკეთებას',
  'filters.engineSize': 'ძრავის მოცულობა',
  'filters.selectEngineSize': 'აირჩიეთ მოცულობა',
  'filters.location': 'ლოკაცია',
  'filters.selectCity': 'აირჩიეთ ქალაქი',
  'filters.category': 'კატეგორია',
  'filters.selectCategory': 'აირჩიეთ კატეგორია',
  'filters.sport': 'სპორტული',
  'filters.utility': 'საკომუნალო',
  'filters.youth': 'ახალგაზრდობისთვის',
  'filters.touring': 'ტურისტული',
  'filters.racing': 'რასინგი',
  'filters.recreational': 'გასართობი',
  'filters.applyFilters': 'ფილტრების გამოყენება',
  'filters.clearFilters': 'ფილტრების გასუფთავება',
  'login.title': 'შესვლა თქვენს ანგარიშში',
  'login.email': 'ელ-ფოსტა',
  'login.password': 'პაროლი',
  'login.button': 'შესვლა',
  'login.forgotPassword': 'დაგავიწყდათ პაროლი?',
  'login.noAccount': 'არ გაქვთ ანგარიში?',
  'login.signUp': 'რეგისტრაცია',
  'sellMyATV.hero.title': 'გაყიდეთ თქვენი კვადრო',
  'sellMyATV.hero.subtitle': 'მიაღწიეთ ათასობით მყიდველს მთელ ქვეყანაში',
  'sellMyATV.hero.button': 'გაყიდვის დაწყება',
  'contact.title': 'დაგვიკავშირდით',
  'about.title': 'ATV Trader-ის შესახებ',
  'terms.title': 'მომსახურების პირობები',
  'privacy.title': 'კონფიდენციალურობის პოლიტიკა',
  'signup.title': 'შექმენით თქვენი ანგარიში',
  'blog.title': 'ბლოგი',
  'research.title': 'კვლევა',
  'dealers.title': 'კვადროების დილერები',
};

const language = ref('ka'); // Default to Georgian

export function useLanguage() {
  const setLanguage = (lang) => {
    language.value = lang;
    localStorage.setItem('language', lang);
  };

  // Load from localStorage on initialization
  if (typeof window !== 'undefined') {
    const savedLanguage = localStorage.getItem('language');
    if (savedLanguage) {
      language.value = savedLanguage;
    }
  }

  const t = (key) => {
    const translations = language.value === 'en' ? enTranslations : kaTranslations;
    return translations[key] || key;
  };

  return {
    language: computed(() => language.value),
    setLanguage,
    t,
  };
}

